#!/usr/bin/env bash

trap 'echo Fatal Error: $0: line $LINENO: installation failed.; exit 1' ERR INT
set -euo pipefail

if [ -z "${DOTPATH:-}" ]; then
  DOTPATH=~/.dotfiles
  export DOTPATH
fi
DOTFILES_GITHUB=https://github.com/ikuo-suyama/dotfiles

# use colors on terminal
tput=$(which tput)
if [ -n "$tput" ]; then
  ncolors=$($tput colors)
fi
if [ -t 1 ] && [ -n "$ncolors" ] && [ "$ncolors" -ge 8 ]; then
  RED="$(tput setaf 1)"
  GREEN="$(tput setaf 2)"
  YELLOW="$(tput setaf 3)"
  BLUE="$(tput setaf 4)"
  BOLD="$(tput bold)"
  NORMAL="$(tput sgr0)"
else
  RED=""
  GREEN=""
  YELLOW=""
  BLUE=""
  BOLD=""
  NORMAL=""
fi

## Logger
info() {
  printf "${GREEN}"
  echo -n " [INFO] "
  printf "${NORMAL}"
  echo "$1"
}

warn() {
  printf "${YELLOW}"
  echo -n " [WARN] "
  printf "${NORMAL}"
  echo "$1"
}

error() {
  printf "${RED}"
  echo -n " [ERROR] "
  printf "${NORMAL}"
  echo "$1"
}

log() {
  echo "  $1"
}

newline() {
  echo ""
}

# utils
is_exists() {
  which "$1" >/dev/null 2>&1
  return $?
}

# installer
dotfiles_download() {
  if [ -d "$DOTPATH" ]; then
    error "💥 $DOTPATH: already exists"
    exit 1
  fi

  newline
  info "🚀 Downloading dotfiles..."
  if is_exists "git"; then
    git clone --recursive "$DOTFILES_GITHUB" "$DOTPATH"

  elif is_exists "curl" || is_exists "wget"; then
    # curl or wget
    local tarball="https://github.com/ikuo-suyama/dotfiles/archive/master.tar.gz"
    if is_exists "curl"; then
      curl -L "$tarball"

    elif is_exists "wget"; then
      wget -O - "$tarball"

    fi | tar xvz
    if [ ! -d dotfiles-master ]; then
      error "💥 Downloaded dir: dotfiles-master does not found"
      exit 1
    fi
    command mv -f dotfiles-master "$DOTPATH"

  else
    error "💥 curl or wget required"
    exit 1
  fi

  info "✅ ...Downloaded."
  newline
}

dotfiles_deploy() {
  newline
  info "✍ Deploying dotfiles..."

  if [ ! -d $DOTPATH ]; then
    error "💥 $DOTPATH: not found"
    exit 1
  fi

  cd "$DOTPATH"

  make deploy
  newline
  info "✅ ...Deploied."
}

## Start installation
dotfiles_logo='
                           __  _       __                             
     ____ ___  ____ ______/ /_(_)___  / /___ _   _____  _____________ 
    / __ `__ \/ __ `/ ___/ __/ / __ \/ / __ \ | / / _ \/ ___/ ___/ _ \
   / / / / / / /_/ / /  / /_/ / / / / / /_/ / |/ /  __/ /  (__  )  __/
  /_/ /_/ /_/\__,_/_/   \__/_/_/ /_/_/\____/|___/\___/_/  /____/\___/ 

   ** WHAT IS INSIDE? ***
  1. Download my dotfiles from '$DOTFILES_GITHUB'
  2. Symlinking dotfiles to your home directory
  3. Install packages
     for debian: [dnsutils vim git tmux curl fish]
     for mac: [brew, @see etc/mac/Brewfile]
'

printf "${BOLD}"
echo "$dotfiles_logo"
printf "${NORMAL}"

newline
read -p "$(warn '❗ Are you sure you want to install it? [y/N] ')" -n 1 -r

if [[ ! $REPLY =~ ^[Yy]$ ]]; then
  newline
  error 'Installation canceled.'
  exit 1
fi

newline
info "👉 Start install the dotfiles."

# dotfiles_download
dotfiles_deploy
# install_packages

info "✨ Installation completed. Enjoy!"
