name: Test Installation

on:
   push:
    branches:
      - master

jobs:
  test-installation-on-host:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
       os: [ubuntu-latest, ubuntu-20.04, macos-latest]
      fail-fast: false
    env:
      TERM: screen-256color
      INSTALL_ANYWAY: Yes
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      # for debugging...
      # - name: Setup tmate session
        # uses: mxschmitt/action-tmate@v1
      - name: Run Installation
        run: |
          curl -fsSL dot.martinloverse.dev | bash
      - name: Use fish
        run: |
          fish

  test-installation-on-alpine:
    runs-on: ubuntu-latest
    container: alpine
    env:
      TERM: screen-256color
      INSTALL_ANYWAY: Yes
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run Installation
        run: |
          apk add curl bash
          curl -fsSL dot.martinloverse.dev | bash
      - name: Use fish
        run: |
          fish

  test-installation-on-debian:
    runs-on: ubuntu-latest
    container: debian
    env:
      TERM: screen-256color
      INSTALL_ANYWAY: Yes
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run Installation
        run: |
          apt update && apt install -y curl
          curl -fsSL dot.martinloverse.dev | bash
      - name: Use fish
        run: |
          fish
